# Generated by Django 4.0.4 on 2022-05-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("pali", models.CharField(max_length=50)),
                ("sanskrit", models.CharField(blank=True, max_length=50, null=True)),
                ("roman", models.CharField(max_length=50)),
                ("content", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Entries",
                "ordering": ["pali"],
            },
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.UniqueConstraint(fields=("pali", "sanskrit"), name="unique_sanskrit"),
        ),
    ]
