# Generated by Django 4.0.4 on 2022-05-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('pali', models.CharField(max_length=20)),
                ('roman', models.CharField(blank=True, max_length=20, null=True)),
                ('sanskrit', models.CharField(blank=True, max_length=20, null=True)),
                ('grammar', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ['pali'],
            },
        ),
    ]
